analyzer:
    strong-mode:
        implicit-casts: false
        implicit-dynamic: false
    enable-experiment:
        - non-nullable
        - nonfunction-type-aliases

linter:
    rules:
        - library_names
        - library_prefixes
        - package_api_docs
        - prefer_null_aware_operators
        - prefer_spread_collections
        - unawaited_futures
        - unnecessary_brace_in_string_interps
        - unnecessary_const
        - unnecessary_getters_setters
        - unnecessary_lambdas
        - unnecessary_new
        - unnecessary_null_aware_assignments
        - unnecessary_null_in_if_null_operators
        - unnecessary_parenthesis
        - unnecessary_statements
        - unnecessary_this
        - unrelated_type_equality_checks
        - use_function_type_syntax_for_parameters
        - use_rethrow_when_possible
        - valid_regexps
        - void_checks
