targets:
    $default:
        builders:
            json_serializable: {}

            functional_data: {}

            web3_contract_generator|web3_gen:
                generate_for:
                    include:
                    - "**/SVIndex.abi"
                    - "**/SVIndexBackend.abi"
                    - "**/SVPayments.abi"
