name: svlight
version: 0.0.1

description: >-
    This library provides integration functionality with the SV Light framework--a secure blockchain based voting dapp.

homepage: https://github.com/secure-vote/dart-svlight
repository: https://github.com/secure-vote/dart-svlight

environment:
    sdk: '>=2.10.0 <3.0.0'

dependencies:
    # data and type safety
    adt: ^0.5.0+4
    # fp generally
    dartz: ^0.9.2
    # logging
    # web3
    web3dart: ^1.2.3
    web3_contract: ^0.1.2
    # ethereum_util:
    # web3_contract:
    #     path: "../dart/web3_contract_generator/web3_contract"
    args: ^1.6.0
    crypto: ^2.1.5
    http: ^0.12.2
    logging: ^0.11.4
    path: ^1.7.0
    yaml: ^2.2.1
    json_annotation: ^3.1.0

dev_dependencies:
    # testing
    test: ^1.15.4
    # dev utilities
    build_runner: ^1.10.3
    # code generators
    adt_annotation: ^0.3.0+2
    web3_contract_generator: ^0.1.3
    json_serializable: ^3.5.0

executables: {}

publish_to: none
